name: SyncPlan Flutter Build
workflows:
  flutter-android-apk:
    name: Build Android APK
    instance_type: windows
    environment:
      flutter: "3.22.0"
    working_directory: .
    scripts:
      - name: Flutter Clean
        script: flutter clean
      - name: Install Dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
